# BSK@L Enterprise - Render Deployment

services:
  - type: web
    name: bskal-enterprise
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend &&npm start
    envVars:
      - key: PORT
        value: 5500
      - key: ADMIN_TOKEN
        generateValue: true
      - key: NODE_ENV
        value: production
